//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRoyalty
    {
        public int BookID { get; set; }
        public Nullable<decimal> RoyaltyRate { get; set; }
        public Nullable<decimal> Advance { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
