//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
        }
    
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string BookTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public int PublisherID { get; set; }
        public string BookImage { get; set; }
        public bool IsSiteFeature { get; set; }
        public bool IsGenreFeature { get; set; }
        public int BookStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual BookRoyalty BookRoyalty { get; set; }
        public virtual BookStatus BookStatus { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
